# Generated by Django 3.1.2 on 2020-10-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default=' ', max_length=100)),
                ('img', models.ImageField(default=' ', upload_to='static/assets/image')),
            ],
        ),
        migrations.CreateModel(
            name='Kenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(default=' ', max_length=200)),
                ('img', models.ImageField(default=' ', upload_to='static/assets/image')),
                ('price', models.IntegerField(default=' ')),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro2.rest')),
            ],
        ),
    ]
